# Generated by Django 5.0.9 on 2026-09-11 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heat_treatment', '0002_initial'),
        ('master_data', '0001_initial'),
        ('masters', '0003_rackmaster_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='heattreatmenttransaction',
            name='operation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heattreatmenttransaction',
            name='surface_finish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.surfacefinish'),
        ),
        migrations.AddField(
            model_name='heattreatmenttransaction',
            name='t_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='T No'),
        ),
        migrations.AddField(
            model_name='heattreatmenttransaction',
            name='tt',
            field=models.CharField(blank=True, max_length=50, verbose_name='TT'),
        ),
        migrations.AlterField(
            model_name='heattreatmenttransaction',
            name='heat_treatment_type',
            field=models.CharField(blank=True, choices=[('annealing', 'Annealing'), ('normalizing', 'Normalizing'), ('hardening', 'Hardening'), ('tempering', 'Tempering'), ('quenching', 'Quenching')], max_length=20),
        ),
        migrations.AlterField(
            model_name='heattreatmenttransaction',
            name='holding_time_minutes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='heattreatmenttransaction',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master_data.employee'),
        ),
        migrations.AlterField(
            model_name='heattreatmenttransaction',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master_data.shift'),
        ),
        migrations.AlterField(
            model_name='heattreatmenttransaction',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='heattreatmenttransaction',
            name='temperature_celsius',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
