# Generated by Django 5.0.9 on 2026-09-11 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heat_treatment', '0004_machine_moved_to_masters'),
        ('masters', '0006_rename_machine_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heattreatmenttransaction',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.machine'),
        ),
    ]
