# Generated by Django 5.0.9 on 2026-09-12 01:56

import apps.heat_treatment.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heat_treatment', '0006_heattreatmenttransaction_completed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HeatBatch',
            fields=[
                ('heat_batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_no', models.CharField(db_index=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], db_index=True, default='in_progress', max_length=15)),
                ('qr_token', models.CharField(db_index=True, default=apps.heat_treatment.models.generate_qr_token, editable=False, help_text='Opaque token the printed QR label points at.', max_length=32, unique=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Heat Batch',
                'verbose_name_plural': 'Heat Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='heattreatmenttransaction',
            name='heat_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='heat_treatment.heatbatch'),
        ),
    ]
