# Generated by Django 5.0.9 on 2026-09-11 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
        ('rolling', '0004_alter_rollingbatch_f_thickness_mm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionlot',
            name='source_rolling_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_lots', to='rolling.rollingbatch'),
        ),
    ]
