# Generated by Django 5.0.9 on 2026-09-30 15:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='order_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pieces', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='order_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='po_date',
            field=models.DateField(blank=True, null=True, verbose_name='PO Date'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='po_number',
            field=models.CharField(blank=True, db_index=True, max_length=60, verbose_name='PO Number'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rs per piece', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='next_action',
            field=models.CharField(blank=True, choices=[('followup', 'Follow-up Call/Visit'), ('initial_introduction', 'Initial Introduction'), ('requirement_discussion', 'Requirement Discussion'), ('sample_requested', 'Sample Requested'), ('sample_delivered', 'Sample Delivered'), ('trial', 'Trial'), ('trial_followup', 'Trial Follow-up'), ('order_discussion', 'Order Discussion'), ('order_received', 'Order Received'), ('repeat_order_followup', 'Repeat Order Follow-up'), ('repeat_order', 'Repeat Order'), ('no_further_action', 'No Further Action')], max_length=30),
        ),
        migrations.AlterField(
            model_name='lead',
            name='stage',
            field=models.CharField(choices=[('initial_introduction', 'Initial Introduction'), ('requirement_discussion', 'Requirement Discussion'), ('sample_requested', 'Sample Requested'), ('sample_delivered', 'Sample Delivered'), ('trial', 'Trial'), ('trial_followup', 'Trial Follow-up'), ('order_discussion', 'Order Discussion'), ('order_received', 'Order Received'), ('repeat_order_followup', 'Repeat Order Follow-up'), ('repeat_order', 'Repeat Order'), ('no_further_action', 'No Further Action')], db_index=True, default='initial_introduction', max_length=30),
        ),
        migrations.AlterField(
            model_name='leadevent',
            name='next_action',
            field=models.CharField(blank=True, choices=[('followup', 'Follow-up Call/Visit'), ('initial_introduction', 'Initial Introduction'), ('requirement_discussion', 'Requirement Discussion'), ('sample_requested', 'Sample Requested'), ('sample_delivered', 'Sample Delivered'), ('trial', 'Trial'), ('trial_followup', 'Trial Follow-up'), ('order_discussion', 'Order Discussion'), ('order_received', 'Order Received'), ('repeat_order_followup', 'Repeat Order Follow-up'), ('repeat_order', 'Repeat Order'), ('no_further_action', 'No Further Action')], max_length=30),
        ),
        migrations.AlterField(
            model_name='leadevent',
            name='stage',
            field=models.CharField(choices=[('initial_introduction', 'Initial Introduction'), ('requirement_discussion', 'Requirement Discussion'), ('sample_requested', 'Sample Requested'), ('sample_delivered', 'Sample Delivered'), ('trial', 'Trial'), ('trial_followup', 'Trial Follow-up'), ('order_discussion', 'Order Discussion'), ('order_received', 'Order Received'), ('repeat_order_followup', 'Repeat Order Follow-up'), ('repeat_order', 'Repeat Order'), ('no_further_action', 'No Further Action')], max_length=30),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminder_type',
            field=models.CharField(choices=[('lead_followup', 'Lead Follow-up'), ('sample_followup', 'Sample Follow-up'), ('trial_followup', 'Trial Follow-up'), ('repeat_trial', 'Repeat Trial'), ('order_followup', 'Order Follow-up'), ('repeat_order', 'Repeat Order'), ('activity', 'Activity')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='required_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Required M'),
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('visit_type', models.CharField(choices=[('mill_visit', 'Mill Visit'), ('phone_call', 'Phone Call'), ('online_meeting', 'Online Meeting'), ('office_visit', 'Office Visit')], default='mill_visit', max_length=20)),
                ('visit_date', models.DateField(db_index=True)),
                ('visit_time', models.TimeField(blank=True, null=True)),
                ('purpose', models.CharField(choices=[('initial_introduction', 'Initial Introduction'), ('requirement_discussion', 'Requirement Discussion'), ('sample_requested', 'Sample Requested'), ('sample_delivered', 'Sample Delivered'), ('trial', 'Trial'), ('trial_followup', 'Trial Follow-up'), ('order_discussion', 'Order Discussion'), ('order_received', 'Order Received'), ('repeat_order_followup', 'Repeat Order Follow-up'), ('repeat_order', 'Repeat Order')], db_index=True, max_length=30, verbose_name='Purpose of Visit')),
                ('people_met', models.CharField(blank=True, max_length=300)),
                ('summary', models.TextField(blank=True, verbose_name='Discussion Summary / Remarks')),
                ('outcome', models.CharField(blank=True, max_length=60)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('next_action', models.CharField(choices=[('followup', 'Follow-up Call/Visit'), ('initial_introduction', 'Initial Introduction'), ('requirement_discussion', 'Requirement Discussion'), ('sample_requested', 'Sample Requested'), ('sample_delivered', 'Sample Delivered'), ('trial', 'Trial'), ('trial_followup', 'Trial Follow-up'), ('order_discussion', 'Order Discussion'), ('order_received', 'Order Received'), ('repeat_order_followup', 'Repeat Order Follow-up'), ('repeat_order', 'Repeat Order'), ('no_further_action', 'No Further Action')], max_length=30)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('followup_overridden', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='sales.activity')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sales.millcontact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='sales.lead')),
                ('mill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='sales.mill')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='sales.salesorder')),
                ('trial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='sales.trialorder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visit_date', '-visit_time', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='leadevent',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='sales.visit'),
        ),
    ]
