# Generated by Django 5.0.9 on 2026-09-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('production_manager', 'Production Manager'), ('rolling_operator', 'Rolling Operator'), ('forming_operator', 'Forming Operator'), ('heat_treatment_operator', 'Heat Treatment Operator'), ('finishing_operator', 'Finishing Operator'), ('finished_goods_operator', 'Finished Goods Operator'), ('quality_inspector', 'Quality Inspector'), ('inventory_manager', 'Inventory Manager'), ('viewer', 'Viewer'), ('sales_admin', 'Sales Admin'), ('sales_executive', 'Sales Executive')], max_length=40, unique=True),
        ),
    ]
