# Generated by Django 5.0.9 on 2026-09-11 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finishing', '0001_initial'),
        ('master_data', '0001_initial'),
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='finishingtransaction',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_operations', to='production.productionlot'),
        ),
        migrations.AddField(
            model_name='finishingtransaction',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master_data.machine'),
        ),
        migrations.AddField(
            model_name='finishingtransaction',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master_data.employee'),
        ),
        migrations.AddField(
            model_name='finishingtransaction',
            name='rejection_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='master_data.reasoncode'),
        ),
        migrations.AddField(
            model_name='finishingtransaction',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master_data.shift'),
        ),
        migrations.AddField(
            model_name='finishingtransaction',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='finishingtransaction',
            index=models.Index(fields=['transaction_number'], name='finishing_f_transac_d3f415_idx'),
        ),
        migrations.AddIndex(
            model_name='finishingtransaction',
            index=models.Index(fields=['status'], name='finishing_f_status_9d3d5f_idx'),
        ),
    ]
