# Generated by Django 5.0.9 on 2026-09-11 10:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RackMaster',
            fields=[
                ('rack_id', models.AutoField(primary_key=True, serialize=False)),
                ('rack_code', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['rack_code'],
            },
        ),
        migrations.CreateModel(
            name='SurfaceFinish',
            fields=[
                ('finish_id', models.AutoField(primary_key=True, serialize=False)),
                ('finish_name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['finish_name'],
            },
        ),
        migrations.CreateModel(
            name='TravellerNo',
            fields=[
                ('traveller_no_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=5, unique=True)),
                ('label', models.CharField(blank=True, default='Pending label', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='WireSerialCounter',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('current_prefix', models.CharField(max_length=2)),
                ('current_number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DiameterMaster',
            fields=[
                ('raw_material_id', models.CharField(help_text='e.g. RM-093', max_length=10, primary_key=True, serialize=False)),
                ('diameter_mm', models.DecimalField(decimal_places=2, max_digits=6, unique=True)),
                ('unit', models.CharField(default='KG', max_length=10)),
                ('total_stock', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('active_coils', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
            ],
            options={
                'ordering': ['diameter_mm'],
                'indexes': [models.Index(fields=['diameter_mm'], name='masters_dia_diamete_af4a72_idx')],
            },
        ),
        migrations.CreateModel(
            name='TravellerType',
            fields=[
                ('traveller_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('seq_no', models.PositiveIntegerField(help_text='Row number in the official master list (1-68).', unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['seq_no'],
                'indexes': [models.Index(fields=['name'], name='masters_tra_name_91107b_idx')],
            },
        ),
        migrations.CreateModel(
            name='DiameterTravellerMapping',
            fields=[
                ('mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('f_thickness_mm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('f_width_mm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traveller_mappings', to='masters.diametermaster')),
                ('traveller_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mapping', to='masters.travellertype')),
            ],
        ),
        migrations.CreateModel(
            name='CoilMaster',
            fields=[
                ('coil_id', models.AutoField(primary_key=True, serialize=False)),
                ('coil_display_number', models.PositiveIntegerField()),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('In Stock', 'In Stock'), ('Consumed', 'Consumed')], default='In Stock', max_length=15)),
                ('supplier', models.CharField(blank=True, max_length=100)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coils', to='masters.diametermaster')),
                ('rack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coils', to='masters.rackmaster')),
            ],
            options={
                'ordering': ['raw_material', 'coil_display_number'],
                'indexes': [models.Index(fields=['raw_material', 'status'], name='masters_coi_raw_mat_a247bf_idx')],
            },
        ),
    ]
