# Generated by Django 5.0.9 on 2026-09-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WireSerialMaster',
            fields=[
                ('serial_id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_no', models.CharField(db_index=True, max_length=10, unique=True)),
                ('prefix', models.CharField(db_index=True, max_length=2)),
                ('sequence', models.PositiveIntegerField(help_text='1-1000 within the prefix block.')),
                ('sort_order', models.PositiveIntegerField(help_text='Global issue order across all prefixes.', unique=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Used', 'Used')], db_index=True, default='Available', max_length=10)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Wire Serial',
                'verbose_name_plural': 'Wire Serials',
                'ordering': ['sort_order'],
            },
        ),
        migrations.DeleteModel(
            name='WireSerialCounter',
        ),
        migrations.AddIndex(
            model_name='wireserialmaster',
            index=models.Index(fields=['status', 'sort_order'], name='masters_wir_status_51fd7a_idx'),
        ),
    ]
