# Generated by Django 5.0.9 on 2026-09-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_wireserialmaster_delete_wireserialcounter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rackmaster',
            name='capacity',
            field=models.PositiveIntegerField(default=10, help_text='Number of coil slots on this rack.'),
        ),
    ]
