# Generated by Django 5.0.9 on 2026-09-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_rackmaster_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travellerno',
            name='label',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
