# Generated by Django 5.0.9 on 2026-09-12 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_rename_machine_table'),
        ('production', '0003_backfill_completed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RackZone',
            fields=[
                ('zone_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='e.g. FORMING, FG', max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('process_slug', models.CharField(db_index=True, help_text='Slug of the process whose completion/receipt places material on this zone.', max_length=30)),
                ('rack_count', models.PositiveIntegerField(default=1)),
                ('rows', models.PositiveIntegerField(default=5)),
                ('columns', models.PositiveIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Rack Zone',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='StorageRack',
            fields=[
                ('rack_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('position', models.PositiveIntegerField(help_text='1-based position of this rack within its zone.')),
                ('is_active', models.BooleanField(default=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='masters.rackzone')),
            ],
            options={
                'ordering': ['zone', 'position'],
            },
        ),
        migrations.CreateModel(
            name='RackSlot',
            fields=[
                ('slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('row', models.PositiveIntegerField()),
                ('column', models.PositiveIntegerField()),
                ('placed_at', models.DateTimeField(blank=True, null=True)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rack_slots', to='production.productionlot')),
                ('placed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='masters.rackzone')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='masters.storagerack')),
            ],
            options={
                'ordering': ['rack__position', 'row', 'column'],
            },
        ),
        migrations.CreateModel(
            name='RackPlacement',
            fields=[
                ('placement_id', models.AutoField(primary_key=True, serialize=False)),
                ('placed_at', models.DateTimeField()),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('released_reason', models.CharField(blank=True, default='', max_length=200)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rack_placements', to='production.productionlot')),
                ('placed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='masters.rackslot')),
            ],
            options={
                'ordering': ['-placed_at'],
                'indexes': [models.Index(fields=['lot', 'released_at'], name='masters_rac_lot_id_3a5526_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='storagerack',
            constraint=models.UniqueConstraint(fields=('zone', 'code'), name='unique_zone_rack_code'),
        ),
        migrations.AddConstraint(
            model_name='storagerack',
            constraint=models.UniqueConstraint(fields=('zone', 'position'), name='unique_zone_rack_position'),
        ),
        migrations.AddIndex(
            model_name='rackslot',
            index=models.Index(fields=['zone', 'lot'], name='masters_rac_zone_id_35cc51_idx'),
        ),
        migrations.AddConstraint(
            model_name='rackslot',
            constraint=models.UniqueConstraint(fields=('rack', 'row', 'column'), name='unique_rack_slot_position'),
        ),
        migrations.AddConstraint(
            model_name='rackslot',
            constraint=models.UniqueConstraint(condition=models.Q(('lot__isnull', False)), fields=('zone', 'lot'), name='unique_zone_lot_slot'),
        ),
    ]
