# Generated by Django 5.0.9 on 2026-09-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_rackzone_storagerack_rackslot_rackplacement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchNoFormat',
            fields=[
                ('format_id', models.AutoField(primary_key=True, serialize=False)),
                ('process_slug', models.CharField(db_index=True, help_text='Slug of the process whose batches this format numbers.', max_length=30)),
                ('regex', models.CharField(help_text='Full-match pattern, e.g. ^B\\d{3}$', max_length=100)),
                ('prefix', models.CharField(blank=True, default='', help_text='e.g. B', max_length=10)),
                ('pad', models.PositiveSmallIntegerField(default=3, help_text='Digits after the prefix.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Batch No Format',
                'ordering': ['process_slug'],
            },
        ),
    ]
