# Generated by Django 5.0.9 on 2026-09-11 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RollingBatch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('wire_serial', models.CharField(db_index=True, editable=False, max_length=10, unique=True)),
                ('wire_diameter_mm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('f_thickness_mm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('f_width_mm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('required_box', models.PositiveIntegerField()),
                ('wire_weight_issued_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed')], db_index=True, default='In Progress', max_length=15)),
                ('rolled_thickness_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rolled_width_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('finished_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('wastage_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('finish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rolling_batches', to='masters.surfacefinish')),
                ('traveller_no', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rolling_batches', to='masters.travellerno')),
                ('traveller_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rolling_batches', to='masters.travellertype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RollingBatchCoil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_taken_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coils_used', to='rolling.rollingbatch')),
                ('coil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rolling_batch_uses', to='masters.coilmaster')),
            ],
        ),
        migrations.AddIndex(
            model_name='rollingbatch',
            index=models.Index(fields=['wire_serial'], name='rolling_rol_wire_se_12dc4c_idx'),
        ),
        migrations.AddIndex(
            model_name='rollingbatch',
            index=models.Index(fields=['status'], name='rolling_rol_status_006290_idx'),
        ),
        migrations.AddConstraint(
            model_name='rollingbatchcoil',
            constraint=models.UniqueConstraint(fields=('batch', 'coil'), name='unique_batch_coil'),
        ),
    ]
