# Generated by Django 5.0.9 on 2026-09-11 07:57

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RollingTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_number', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('input_quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('output_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('rejection_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_operations', to='production.productionlot')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master_data.machine')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master_data.employee')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rolling_transactions', to='master_data.materialmaster')),
                ('rejection_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='master_data.reasoncode')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master_data.shift')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_number'], name='rolling_rol_transac_3ddff8_idx'), models.Index(fields=['status'], name='rolling_rol_status_3b1c4a_idx')],
            },
        ),
    ]
