# Generated by Django 5.0.9 on 2026-09-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollingbatch',
            name='status',
            field=models.CharField(choices=[('In Progress', 'Rolling Inprogress'), ('Completed', 'Rolling Completed')], db_index=True, default='In Progress', max_length=15),
        ),
    ]
