# Generated by Django 5.0.9 on 2026-09-11 11:54

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolling', '0002_alter_rollingbatch_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollingbatch',
            name='f_thickness_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='rollingbatch',
            name='f_width_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='rollingbatch',
            name='required_box',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rollingbatch',
            name='status',
            field=models.CharField(choices=[('Draft', 'Rolling Draft'), ('In Progress', 'Rolling Inprogress'), ('Completed', 'Rolling Completed')], db_index=True, default='In Progress', max_length=15),
        ),
        migrations.AlterField(
            model_name='rollingbatch',
            name='wire_diameter_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='rollingbatch',
            name='wire_serial',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='rollingbatch',
            name='wire_weight_issued_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.CreateModel(
            name='RollingTransaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_date', models.DateField(db_index=True)),
                ('full_boxes', models.PositiveIntegerField(default=0, help_text='Complete boxes - eligible to move to the next stage.')),
                ('partial_qty', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Quantity in the part-filled box - held back, not sent to the next stage.', max_digits=8)),
                ('produced_weight_kg', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('rolled_thickness_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rolled_width_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('moved_to_next_stage', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='rolling.rollingbatch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
                'indexes': [models.Index(fields=['batch', 'transaction_date'], name='rolling_rol_batch_i_9329e0_idx')],
            },
        ),
    ]
