# Generated by Django 5.0.9 on 2026-09-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolling', '0003_alter_rollingbatch_f_thickness_mm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollingbatch',
            name='f_thickness_mm',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='rollingbatch',
            name='f_width_mm',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='rollingbatch',
            name='required_box',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='rollingbatch',
            name='status',
            field=models.CharField(choices=[('In Progress', 'Rolling Inprogress'), ('Completed', 'Rolling Completed')], db_index=True, default='In Progress', max_length=15),
        ),
        migrations.AlterField(
            model_name='rollingbatch',
            name='wire_diameter_mm',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='rollingbatch',
            name='wire_serial',
            field=models.CharField(db_index=True, editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='rollingbatch',
            name='wire_weight_issued_kg',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.DeleteModel(
            name='RollingTransaction',
        ),
    ]
