# Generated by Django 5.0.9 on 2026-09-11 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forming', '0002_initial'),
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formingtransaction',
            name='operation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formingtransaction',
            name='traveller_length_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='formingtransaction',
            name='traveller_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='formingtransaction',
            name='wastage_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='formingtransaction',
            name='wastage_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='formingtransaction',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master_data.employee'),
        ),
        migrations.AlterField(
            model_name='formingtransaction',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master_data.shift'),
        ),
        migrations.AlterField(
            model_name='formingtransaction',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
