# Generated by Django 5.0.9 on 2026-09-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forming', '0005_alter_formingtransaction_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='formingtransaction',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
