# Generated by Django 5.0.9 on 2026-09-11 07:57

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterialStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('status', models.CharField(choices=[('available', 'Available'), ('hold', 'Hold'), ('rejected', 'Rejected')], default='available', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adjustment_number', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('stock_type', models.CharField(choices=[('raw_material', 'Raw Material'), ('wip', 'WIP'), ('finished_goods', 'Finished Goods')], max_length=20)),
                ('quantity_before', models.DecimalField(decimal_places=3, max_digits=14)),
                ('quantity_after', models.DecimalField(decimal_places=3, max_digits=14)),
                ('remarks', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock_type', models.CharField(choices=[('raw_material', 'Raw Material'), ('wip', 'WIP'), ('finished_goods', 'Finished Goods')], db_index=True, max_length=20)),
                ('movement_type', models.CharField(choices=[('receipt', 'Receipt'), ('issue', 'Issue'), ('production_consumption', 'Production Consumption'), ('production_output', 'Production Output'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('adjustment', 'Adjustment'), ('rejection', 'Rejection')], db_index=True, max_length=25)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=3, max_digits=14)),
                ('reference_number', models.CharField(blank=True, db_index=True, max_length=40)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transfer_number', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('stock_type', models.CharField(choices=[('raw_material', 'Raw Material'), ('wip', 'WIP'), ('finished_goods', 'Finished Goods')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('remarks', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WIPStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('raw_material', 'Raw Material'), ('rolling', 'Rolling'), ('forming', 'Forming'), ('heat_treatment', 'Heat Treatment'), ('finishing', 'Finishing'), ('finished_goods', 'Finished Goods')], db_index=True, max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('status', models.CharField(choices=[('available', 'Available'), ('hold', 'Hold'), ('rejected', 'Rejected')], default='available', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FinishedGoodsStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fg_lot_number', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('accepted_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('rejected_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('quality_approved', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('available', 'Available'), ('hold', 'Hold'), ('rejected', 'Rejected')], default='hold', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fg_stock', to='master_data.location')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
