# Generated by Django 5.0.9 on 2026-09-11 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0001_initial'),
        ('master_data', '0001_initial'),
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedgoodsstock',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finished_goods', to='production.productionlot'),
        ),
        migrations.AddField(
            model_name='finishedgoodsstock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fg_stock', to='master_data.productmaster'),
        ),
        migrations.AddField(
            model_name='finishedgoodsstock',
            name='quality_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finishedgoodsstock',
            name='rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fg_stock', to='master_data.rack'),
        ),
        migrations.AddField(
            model_name='finishedgoodsstock',
            name='shelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fg_stock', to='master_data.shelf'),
        ),
        migrations.AddField(
            model_name='finishedgoodsstock',
            name='tray',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fg_stock', to='master_data.tray'),
        ),
        migrations.AddField(
            model_name='finishedgoodsstock',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rawmaterialstock',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rawmaterialstock',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_material_stock', to='master_data.location'),
        ),
        migrations.AddField(
            model_name='rawmaterialstock',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_records', to='master_data.materialmaster'),
        ),
        migrations.AddField(
            model_name='rawmaterialstock',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master_data.location'),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='production.productionlot'),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master_data.materialmaster'),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master_data.reasoncode'),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master_data.location'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='production.productionlot'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master_data.materialmaster'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master_data.productmaster'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='from_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='master_data.location'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='production.productionlot'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='master_data.materialmaster'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='to_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='master_data.location'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wipstock',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wipstock',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wip_stock', to='master_data.location'),
        ),
        migrations.AddField(
            model_name='wipstock',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wip_stock', to='production.productionlot'),
        ),
        migrations.AddField(
            model_name='wipstock',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='finishedgoodsstock',
            index=models.Index(fields=['fg_lot_number'], name='inventory_f_fg_lot__996725_idx'),
        ),
        migrations.AddIndex(
            model_name='finishedgoodsstock',
            index=models.Index(fields=['status'], name='inventory_f_status_29278c_idx'),
        ),
        migrations.AddIndex(
            model_name='rawmaterialstock',
            index=models.Index(fields=['material'], name='inventory_r_materia_751118_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rawmaterialstock',
            unique_together={('material', 'location', 'status')},
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['stock_type'], name='inventory_s_stock_t_a10357_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['created_at'], name='inventory_s_created_ff5dbb_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['reference_number'], name='inventory_s_referen_e3d80f_idx'),
        ),
        migrations.AddIndex(
            model_name='wipstock',
            index=models.Index(fields=['stage'], name='inventory_w_stage_c658fe_idx'),
        ),
        migrations.AddIndex(
            model_name='wipstock',
            index=models.Index(fields=['lot'], name='inventory_w_lot_id_6939a0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wipstock',
            unique_together={('stage', 'lot', 'location', 'status')},
        ),
    ]
