# Generated by Django 5.0.9 on 2026-09-12 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        ('master_data', '0002_delete_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedgoodsstock',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fg_stock', to='master_data.location'),
        ),
    ]
