# Generated by Django 5.0.9 on 2026-10-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_finishedgoodsstock_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedgoodsstock',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('hold', 'Hold'), ('rejected', 'Rejected'), ('dispatched', 'Dispatched')], default='hold', max_length=10),
        ),
    ]
